### ISSUE TITLE
Change the command "vwgen set" syntax use of the term "endpoint" to instead use the industry VxLAN term "VTEP" or perhaps "VTEP_IP" 

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#12]
This  is related to the Closed Issue #8 that you've already corrected:
**https://github.com/m13253/VxWireguard-Generator/issues/8**

In the current VxWireguard-Generator README there are examples of the vwgen command to set what you call "endpoints" in the examples:

> \# Set endpoint of node1 and node2 to their public IP addresses (either IPv4 or IPv6 will work), leave empty for node3 so it will do auto-discovery
> vwgen set wg-meshvpn node node1 **endpoint** '[2001:db8:1::1]:1234' listen-port 1234
> vwgen set wg-meshvpn node node2 **endpoint** '[2001:db8:2::1]:2345' listen-port 2345

In my view, what you are calling end-points are what the industry calls _VxLAN Virtual Tunnel End Points or **VTEP**_

You previously corrected this for the command **vwgen showconf** output to correctly identify the VTEP IP of a Node's VxLAN connection.

_I'd like to suggest changing the "**vwgen set**" command_ syntax to use something like "**VTEP**" or "**VTEP_IP**" instead of the term "**endpoint**" to enhance the consistancy of the syntax.   This would make sure that the person installing/configuring things understands that the command is configuring the VxLAN Virtual Tunnel End Poiont (VTEP) of that Node's VxLAN tunnel.

![vtep](https://user-images.githubusercontent.com/1682855/89319355-ffc2be00-d64d-11ea-9021-bd7e40224fc7.png)

**Comment by m13253** [comment]
> In my view, what you are calling end-points are what the industry calls _VxLAN Virtual Tunnel End Points or **VTEP**_

Actually the "endpoint" here is the Wireguard endpoint, not VTEP.
VTEP is automatically assigned by the program from a pool.
(In fact, VTEP address is chosen from the 169.254.0.0/16 block by default, to deliberately disallow routing on this layer.)

The reason I choose "endpoint" is to maintain CLI-similarity with Wireguard's official tools.
