### ISSUE TITLE
Following example - vwget add wg-meshvpn throws a TypeError

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#5]
Closed this because the error was caused by having too old a Python version installed.

Following the "example"...  when I get to execution of the following I get the TypeError below...

> $ **vwgen add wg-meshvpn**
> 
> $ vwgen add wg-meshvpn
> Traceback (most recent call last):
>   File "/usr/local/bin/vwgen", line 11, in <module>
>     load_entry_point('VxWireguard-Generator==1.0', 'console_scripts', 'vwgen')()
>   File "/usr/local/lib/python3.6/dist-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/__main__.py", line 30, in __main__
>   File "/usr/local/lib/python3.6/dist-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/vwgen.py", line 38, in main
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/vwgen_add.py", line 31, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
>   File "/usr/local/lib/python3.6/dist-packages/VxWireguard_Generator-1.0-py3.6.egg/vwgen/common.py", line 57, in <module>
> **_TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases_**

**Comment by m13253** [comment]
Please try to use a newer Python (e.g. 3.7 or 3.8). This might fix the problem.

**Comment by bmullan** [comment]
Yeah I realized that & closed the issue

Thanks
