### ISSUE TITLE
question regarding example config IPv6 addresses in repo README.md file

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#6]
In the following Example for the commands highlighted I'm guessing that those Ipv6 addresses
are coming from the IPv6 "Pool" and are the TEPs?

*So were does the installer configure the actual physical Servers IP addresses so later in the instructions the Configurator (and configuration setsp) know where the machines are that need
the config for Node1, Node2, Node3?*

Are those real IPs meant to be edited into the **wg-meshvpn.conf** file?

If so where?   the linklayer address and allowed-ips statements?

Lastly, some cloud servers ONLY have an IPv6 Link Local address and an IPv4 address.
What do I do about those?

thanks for any guidance.

Brian

> \# Find a good place to store the data
> mkdir -p ~/Documents/vwnetworks
> cd ~/Documents/vwnetworks
> 
> \# Add a mesh network
> vwgen add wg-meshvpn
> 
> \# Set the address pool of the network
> vwgen set wg-meshvpn pool-ipv4 172.20.10.0/24 pool-ipv6 2001:db8:42::/64
> 
> \# Add 3 nodes
> \# They will have IPv4 addresses fixed and IPv6 addresses dynamically calculated on demand
> vwgen add wg-meshvpn node1 node2 node3
> 
> **\# Set endpoint of node1 and node2, leave empty for node3 so it will do auto-discovery
> vwgen set wg-meshvpn node node1 endpoint '[2001:db8:1::1]:1234' listen-port 1234
> vwgen set wg-meshvpn node node2 endpoint '[2001:db8:2::1]:2345' listen-port 2345
> vwgen set wg-meshvpn node node3 listen-port 3456**
> 
> \# Show all information we have so far
> vwgen show wg-meshvpn
> 
> \# Generate a configuration for node1
> \# It's a bad habit to log into server with root, this is just a demo
> vwgen showconf wg-meshvpn node1 > node1.conf
> scp node1.conf 'root@[2001:db8:1::1]:/etc/wireguard/wg-meshvpn.conf'
> ssh root@2001:db8:1::1 chmod 600 /etc/wireguard/wg-meshvpn.conf \; wg-quick up wg-meshvpn
> 
> \# Generate a configuration for node2
> \# This time we will use systemd to launch wg-quick
> vwgen showconf wg-meshvpn node2 > node2.conf
> scp node1.conf 'root@[2001:db8:2::1]:/etc/wireguard/wg-meshvpn.conf'
> ssh root@2001:db8:2::1 chmod 600 /etc/wireguard/wg-meshvpn.conf \; systemctl start wg-quick@wg-meshvpn
> 
> \# The configuration is stored in plaintext TOML format
> less wg-meshvpn.conf

**Comment by m13253** [comment]
Sorry for the confusion. The real IP addresses are 2001:db8:1::1 for node1 and 2001:db8:2::1 for node2. It can be either IPv4 or IPv6. Please fill in your server's real IP address for `endpoint`.

The virtual IP addresses are taken from `pool-ipv4` and `pool-ipv6`.

Allowed-IPs are managed automatically because VXLAN is run on top of Wireguard layer. The Wireguard layer is not exposed for direct use.

**Comment by bmullan** [comment]
Great, thanks for clearing that up.

I had assumed IPv4 could be used but in
 the README I'm not sure thats mentioned.

Brian

**Comment by m13253** [comment]
Thank you for pointing out. I just updated the Readme.md.
