### ISSUE TITLE
What is process to expand/reduce number of Configs generated above/below initial Node Count 

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#7]
@m13253 

I am wondering  _is there a Best Practice_ you can recommend for this use-case _or would 
VxWireguard need some additional functionality to accomplish it?_

_**Example**_:
- Someone uses VxWireguard and generates configs for 10 Nodes.
- Everything works great.
- Later they want to add another 10 (or 50) Nodes.
- Or later they want to reduce the original 10 Nodes to say 5 Nodes

Is there a **Process** _defined for how to do this **and not incur any changes to the configs of the original 10 Nodes**_?

I know _a worst-case scenario would be to manually edit configs_ but that would seem prone to mistakes & errors by users/admins.

Brian

**Comment by m13253** [comment]
Hello,

Thank you for your message.

The `vwgen showconf <config file> <node name>` command is able to generate the most up-to-date version of configuration file for `wg-quick` use. Placing the generated file at `/etc/wireguard/<iface name>.conf` and issuing a `sudo systemctl restart wg-quick@<iface name>` will trigger a restart with new configuration.

If you run as many as 10 servers, I suggest you use any tools that can execute commands simultaneously for each server. Or you can use a bash `for`-loop to generate and distribute configuration files.

In case my reply does not fully answer solve your question, please feel free to tell me.
