### ISSUE TITLE
re Label Names for IP addresses in vwgen generated config Node config files

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#8]
@m13253 

In using VxWireguard and vwgen to create my individual Node Wireguard/VxLAN configs I noticed something _I wanted to mention *to see if it improves clarity* of the 3 Layers of IP addresses that _**vwgen**_ adds to any one Node's WireGuard Config._

In **[my now closed Issue #4](https://github.com/m13253/VxWireguard-Generator/issues/4)** you said:

> **vwgen has three layers of IP addresses**:
> 1. The **endpoint**. They are the addresses your ISP provided you. Wireguard uses these address to establish tunnels between nodes.
> 2. The **mid-layer.** They are allocated randomly from 169.254.0.0/16 link-local address space, used to build the VXLAN on top of it.
> 3. The **inside address**. They are allocated from `pool-ipv4` and `pool-ipv6`. Since all nodes are now connected to one LAN, preferably you will want these address to reside in one single subnet (or you will have to use some routing protocol to make routing work). If you are not satisfied with the automatic allocation, for IPv4, you can edit the address manually; for IPv6,

---  
One of own example generated configs as an example:

> node: mynode1
>   public key: ggi7A/l9Kuf4iw60GuCsZCdf7LG6rTjzDHIgVpqk4WY=
>   private key: +M1KrSvEgXVZsNjap5HNxEYjzLPd7ucyYLuPU2YPIUw=
>   **endpoint**: [135.181.29.175]:50000
>   listen port: 50000
>   **address**: 172.20.10.204/24, 2001:db8:42:0:c72:2056:9aa4:e166/64
>   allowed ips: 169.254.224.23/32
>   **link-layer address**: 169.254.224.23/16
>   blacklist: 
>   whitelist: vm1

---   
In **[IETF RFC 7348](https://tools.ietf.org/html/rfc7348)** a VXLAN **Virtual Tunnel End Point (VTEP)** is defined in Section 4. as:

> _**The end point of the tunnel (VXLAN Tunnel End Point or   VTEP)**_  

So wouldn't it make sense to rename the LABEL "_**address**_" in the vwgen generated config
to "_**VTEP**_" or perhaps just "_**TEP**_ *(Tunnel End Point*)"?

Next,  
given the *vwgen* generated config is for integration of the network Wireguard and VXLAN, wouldn't it be _**less** confusing_ (again regarding the **[IETF RFC 7348](https://tools.ietf.org/html/rfc7348)** to rename the LABEL "_**endpoint**_"  to something else ?

My suggestion is:
Since "_**endpoint**_" is really the "_**Public IP**_" of "_**that**_" Node wouldn't it be more correct to just call that *vwgen config LABEL* something like "_**public ip**_"  ?

example using my config from above:

> node: mynode1
>   public key: ggi7A/l9Kuf4iw60GuCsZCdf7LG6rTjzDHIgVpqk4WY=
>   private key: +M1KrSvEgXVZsNjap5HNxEYjzLPd7ucyYLuPU2YPIUw=
>   **public ip**: [135.181.29.175]:50000
>   listen port: 50000
>   **vtep address**: 172.20.10.204/24, 2001:db8:42:0:c72:2056:9aa4:e166/64
>   allowed ips: 169.254.224.23/32
>   **link-layer address**: 169.254.224.23/16
>   blacklist: 
>   whitelist: vm1

**Comment by m13253** [comment]
That is a good suggestion!
I fixed it in 0dbedb78b3055fee89eb8ed975754993734464cf.

**Comment by bmullan** [comment]
@m13253 

Since you changed the Labels to "**public ip**" and "**vtep address**" you will need to update the README.md file as it still uses the "**endpoint**" Label instead of the new "**public ip**" Label

Also, the Source Files:   "_**vwgen_add.py**_ & _**vwgen_set.py**_"  still contains references to "endpoint" instead of "_**public ip**_" .

I guess "public ip" might also need to be changed to a single string  like "_**public_ip**_"
