### ISSUE TITLE
feature request - add vwgen cli option to create N number of Node configs using a basename & a number specifying how many

### ISSUE THREAD

**Issue by bmullan** [m13253/VxWireguard-Generator#9]
Could you add a **vwgen** command line option to create a large number of Node configs.

**_example_**:
_

> vwgen add wg-meshvpn node1 node2 node3

_
is fine for 2,3.. maybe 10 Nodes.

But what if you needed 50 Nodes (or more)?   Specifying them all this way would be alot of repetitive typing.

Could some option be created  to do this for the user.

**_example_**:
_

> vwgen add wg-meshvpn nameroot="string"  numbernodes="#"

> where:   nameroot would be something like "node" or "cn" or anything
> where:  numbernodes would be the number of "namerootXX" to
>              maximum number of Node Configs to generate
_

So 
> vwgen add wg-meshvpn nameroot=mycn numbernodes=25

would create 25 Node Configurations and they would be named as a concatenation of
the "nameroot" and the "number" so in the above it would generate:

mycn1
mycn2
mycn3
...
mycn25

The above is just my .02 cents and there may be a better way to do this but I think it would
be helpful to have something like this?

**Comment by m13253** [comment]
What you want might be:
```bash
vwgen add wg-meshvpn $(seq -f 'mycn%.f' 50)
```

**Comment by bmullan** [comment]
@m13253 

Cool I wasn't aware **vwgen** could execute an external program like 'seq'.

This works for me regarding this issue but read the section titled:

> _**The seq command to create standard bash for Loop (outdated method)**_ 

Where it says...  
_

> _WARNING! The **seq** command print a sequence of numbers and it is here due to historical reasons. The following examples is only recommend for older bash version. All users (bash v3.x+) are recommended to use the above syntax._

_

URL:   **https://www.cyberciti.biz/faq/bash-for-loop/**
